-- MySQL Script generated by MySQL Workbench
-- Wed Aug  5 12:08:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP TABLE IF EXISTS `university` ;

CREATE TABLE IF NOT EXISTS `university` (
  `iduniversity` TINYINT NOT NULL,
  `university_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduniversity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `region` ;

CREATE TABLE IF NOT EXISTS `region` (
  `idregion` TINYINT NOT NULL,
  `region_zipcode` INT NOT NULL,
  `university` TINYINT NOT NULL,
  PRIMARY KEY (`idregion`),
  INDEX `university_idx` (`university` ASC) VISIBLE,
  CONSTRAINT `region_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `college`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `college` ;

CREATE TABLE IF NOT EXISTS `college` (
  `idcollege` TINYINT NOT NULL,
  `college_name` VARCHAR(45) NOT NULL,
  `university` TINYINT NOT NULL,
  PRIMARY KEY (`idcollege`),
  INDEX `university_link_idx` (`university` ASC) VISIBLE,
  CONSTRAINT `college_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  `iddepartment` TINYINT NOT NULL,
  `department_name` VARCHAR(45) NOT NULL,
  `college` TINYINT NOT NULL,
  PRIMARY KEY (`iddepartment`),
  INDEX `college_idx` (`college` ASC) VISIBLE,
  CONSTRAINT `dept_college_fk`
    FOREIGN KEY (`college`)
    REFERENCES `college` (`idcollege`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `subject` ;

CREATE TABLE IF NOT EXISTS `subject` (
  `idsubject` TINYINT NOT NULL,
  `subject_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `class` ;

CREATE TABLE IF NOT EXISTS `class` (
  `idclass` TINYINT NOT NULL,
  `class_name` VARCHAR(45) NOT NULL,
  `department` TINYINT NOT NULL,
  `subject` TINYINT NOT NULL,
  `educator` TINYINT NULL,
  PRIMARY KEY (`idclass`),
  INDEX `department_idx` (`department` ASC) VISIBLE,
  INDEX `subject_idx` (`subject` ASC) VISIBLE,
  CONSTRAINT `class_department_fk`
    FOREIGN KEY (`department`)
    REFERENCES `department` (`iddepartment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `class_subject_fk`
    FOREIGN KEY (`subject`)
    REFERENCES `subject` (`idsubject`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `student` ;

CREATE TABLE IF NOT EXISTS `student` (
  `idstudent` TINYINT NOT NULL,
  `student_email` VARCHAR(45) NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semester`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `semester` ;

CREATE TABLE IF NOT EXISTS `semester` (
  `idsemester` TINYINT NOT NULL,
  `semester_season` VARCHAR(45) NOT NULL,
  `university` TINYINT NOT NULL,
  PRIMARY KEY (`idsemester`),
  INDEX `university_idx` (`university` ASC) VISIBLE,
  CONSTRAINT `semester_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

CREATE TABLE IF NOT EXISTS `employee` (
  `employeeid` TINYINT NOT NULL,
  `employee_type` VARCHAR(45) NOT NULL,
  `university` TINYINT NOT NULL,
  INDEX `university_idx` (`university` ASC) VISIBLE,
  PRIMARY KEY (`employeeid`),
  CONSTRAINT `employee_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `educator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `educator` ;

CREATE TABLE IF NOT EXISTS `educator` (
  `ideducator` TINYINT NOT NULL,
  `educator_email` VARCHAR(45) NOT NULL,
  `employee_type` VARCHAR(45) NOT NULL,
  `employee` TINYINT NOT NULL,
  PRIMARY KEY (`ideducator`, `employee`),
  INDEX `educator_employee_fk_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `educator_employee_fk`
    FOREIGN KEY (`employee`)
    REFERENCES `employee` (`employeeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techEngineer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techEngineer` ;

CREATE TABLE IF NOT EXISTS `techEngineer` (
  `idtechEngineer` TINYINT NOT NULL,
  `employee_type` VARCHAR(45) NOT NULL,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee` TINYINT NOT NULL,
  PRIMARY KEY (`idtechEngineer`, `employee`),
  INDEX `fk_techengineer_employee_idx` (`employee` ASC) VISIBLE,
  CONSTRAINT `fk_techengineer_employee`
    FOREIGN KEY (`employee`)
    REFERENCES `employee` (`employeeid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lecture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lecture` ;

CREATE TABLE IF NOT EXISTS `lecture` (
  `idlecture` TINYINT NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `educator` TINYINT NOT NULL,
  PRIMARY KEY (`idlecture`),
  INDEX `lecture_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `lecture_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post` ;

CREATE TABLE IF NOT EXISTS `post` (
  `idpost` TINYINT NOT NULL,
  `post_type` VARCHAR(45) NOT NULL,
  `educator` TINYINT NOT NULL,
  PRIMARY KEY (`idpost`),
  INDEX `post_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `post_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `quiz` ;

CREATE TABLE IF NOT EXISTS `quiz` (
  `idquiz` TINYINT NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `educator` TINYINT NOT NULL,
  PRIMARY KEY (`idquiz`),
  INDEX `quiz_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `quiz_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homework`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `homework` ;

CREATE TABLE IF NOT EXISTS `homework` (
  `idhomework` TINYINT NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `educator` TINYINT NOT NULL,
  PRIMARY KEY (`idhomework`),
  INDEX `homework_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `homework_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `test` ;

CREATE TABLE IF NOT EXISTS `test` (
  `idtest` TINYINT NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `educator` TINYINT NOT NULL,
  PRIMARY KEY (`idtest`),
  INDEX `test_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `test_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grade` ;

CREATE TABLE IF NOT EXISTS `grade` (
  `idgrade` TINYINT NOT NULL,
  `grade_letter` VARCHAR(11) NOT NULL,
  `educator` TINYINT NOT NULL,
  `student` TINYINT NOT NULL,
  INDEX `student_idx` (`student` ASC) VISIBLE,
  PRIMARY KEY (`idgrade`),
  INDEX `grade_educator_fk_idx` (`educator` ASC) VISIBLE,
  CONSTRAINT `grade_student_fk`
    FOREIGN KEY (`student`)
    REFERENCES `student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grade_educator_fk`
    FOREIGN KEY (`educator`)
    REFERENCES `educator` (`ideducator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `website` ;

CREATE TABLE IF NOT EXISTS `website` (
  `URL` VARCHAR(45) NOT NULL,
  `university` TINYINT NOT NULL,
  PRIMARY KEY (`URL`),
  INDEX `university_idx` (`university` ASC) VISIBLE,
  CONSTRAINT `website_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `university` TINYINT NOT NULL,
  PRIMARY KEY (`user_name`),
  INDEX `user_university_fk_idx` (`university` ASC) VISIBLE,
  CONSTRAINT `user_university_fk`
    FOREIGN KEY (`university`)
    REFERENCES `university` (`iduniversity`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

CREATE TABLE IF NOT EXISTS `account` (
  `account_name` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`account_name`),
  INDEX `account_user_fk_idx` (`user` ASC) VISIBLE,
  CONSTRAINT `account_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `user` (`user_name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `archive` ;

CREATE TABLE IF NOT EXISTS `archive` (
  `idarchive` TINYINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idarchive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library` ;

CREATE TABLE IF NOT EXISTS `library` (
  `idlibrary` TINYINT NOT NULL,
  `library_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `region` TINYINT NOT NULL,
  PRIMARY KEY (`idlibrary`),
  INDEX `region_idx` (`region` ASC) VISIBLE,
  CONSTRAINT `library_region_fk`
    FOREIGN KEY (`region`)
    REFERENCES `region` (`idregion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `techSupport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techSupport` ;

CREATE TABLE IF NOT EXISTS `techSupport` (
  `idtechSupport` TINYINT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `techEngineer` TINYINT NOT NULL,
  PRIMARY KEY (`idtechSupport`),
  INDEX `techEngineer_idx` (`techEngineer` ASC) VISIBLE,
  CONSTRAINT `techSupport_techEngineer_fk`
    FOREIGN KEY (`techEngineer`)
    REFERENCES `techEngineer` (`idtechEngineer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `resource` ;

CREATE TABLE IF NOT EXISTS `resource` (
  `URL` VARCHAR(45) NOT NULL,
  `class` TINYINT NOT NULL,
  `semester` TINYINT NOT NULL,
  `archive` TINYINT NOT NULL,
  `library` TINYINT NOT NULL,
  `techSupport` TINYINT NOT NULL,
  `website` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`URL`, `class`, `semester`, `archive`, `library`, `techSupport`),
  INDEX `class_idx` (`class` ASC) VISIBLE,
  INDEX `semester_idx` (`semester` ASC) VISIBLE,
  INDEX `archive_idx` (`archive` ASC) VISIBLE,
  INDEX `library_idx` (`library` ASC) VISIBLE,
  INDEX `techSupport_idx` (`techSupport` ASC) VISIBLE,
  INDEX `website_idx` (`website` ASC) VISIBLE,
  CONSTRAINT `res_class_fk`
    FOREIGN KEY (`class`)
    REFERENCES `class` (`idclass`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `res_semester_fk`
    FOREIGN KEY (`semester`)
    REFERENCES `semester` (`idsemester`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `res_archive_fk`
    FOREIGN KEY (`archive`)
    REFERENCES `archive` (`idarchive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `res_library_fk`
    FOREIGN KEY (`library`)
    REFERENCES `library` (`idlibrary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `res_techSupport_fk`
    FOREIGN KEY (`techSupport`)
    REFERENCES `techSupport` (`idtechSupport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `res_website_fk`
    FOREIGN KEY (`website`)
    REFERENCES `website` (`URL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book` ;

CREATE TABLE IF NOT EXISTS `book` (
  `ISBN` INT NOT NULL,
  `book_name` VARCHAR(45) NOT NULL,
  `library` TINYINT NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `library_idx` (`library` ASC) VISIBLE,
  CONSTRAINT `book_library_fk`
    FOREIGN KEY (`library`)
    REFERENCES `library` (`idlibrary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electronic` ;

CREATE TABLE IF NOT EXISTS `electronic` (
  `idelectronic` TINYINT NOT NULL,
  `library` TINYINT NOT NULL,
  PRIMARY KEY (`idelectronic`),
  INDEX `library_idx` (`library` ASC) VISIBLE,
  CONSTRAINT `electronic_library_fk`
    FOREIGN KEY (`library`)
    REFERENCES `library` (`idlibrary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `multimedia` ;

CREATE TABLE IF NOT EXISTS `multimedia` (
  `idmultimedia` TINYINT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `library` TINYINT NOT NULL,
  PRIMARY KEY (`idmultimedia`),
  INDEX `library_idx` (`library` ASC) VISIBLE,
  CONSTRAINT `multimedia_library_fk`
    FOREIGN KEY (`library`)
    REFERENCES `library` (`idlibrary`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `author` ;

CREATE TABLE IF NOT EXISTS `author` (
  `idauthor` TINYINT NOT NULL,
  `author_name` VARCHAR(45) NOT NULL,
  `book` INT NOT NULL,
  PRIMARY KEY (`idauthor`),
  INDEX `book_idx` (`book` ASC) VISIBLE,
  CONSTRAINT `author_book_fk`
    FOREIGN KEY (`book`)
    REFERENCES `book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ebook` ;

CREATE TABLE IF NOT EXISTS `ebook` (
  `idebook` TINYINT NOT NULL,
  `ebook_genre` VARCHAR(45) NOT NULL,
  `multimedia` TINYINT NOT NULL,
  PRIMARY KEY (`idebook`, `multimedia`),
  INDEX `multimedia_idx` (`multimedia` ASC) VISIBLE,
  CONSTRAINT `ebook_mulitmedia_fk`
    FOREIGN KEY (`multimedia`)
    REFERENCES `multimedia` (`idmultimedia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `audio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audio` ;

CREATE TABLE IF NOT EXISTS `audio` (
  `idaudio` TINYINT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `multimedia` TINYINT NOT NULL,
  PRIMARY KEY (`idaudio`, `multimedia`),
  INDEX `multimedia_idx` (`multimedia` ASC) VISIBLE,
  CONSTRAINT `audio_mulitmedia_fk`
    FOREIGN KEY (`multimedia`)
    REFERENCES `multimedia` (`idmultimedia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `video` ;

CREATE TABLE IF NOT EXISTS `video` (
  `idvideo` TINYINT NOT NULL,
  `video_name` VARCHAR(45) NOT NULL,
  `multimedia` TINYINT NOT NULL,
  PRIMARY KEY (`idvideo`, `multimedia`),
  INDEX `multimedia_idx` (`multimedia` ASC) VISIBLE,
  CONSTRAINT `video_mulitmedia_fk`
    FOREIGN KEY (`multimedia`)
    REFERENCES `multimedia` (`idmultimedia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;